server:
  port: 8888
spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lss
    driver-class-name: com.mysql.jdbc.Driver

  main:
    allow-circular-references: true